# Create/refresh the two desktop shortcuts for the OpenViking memory backend,
# with icons generated by make-icons.ps1.
#
#   OpenViking记忆-启动  ->  powershell -File <root>\start_openviking.ps1
#   OpenViking记忆-停止  ->  powershell -File <root>\stop_openviking.ps1
#
# Both run hidden (WindowStyle 7) and only pop a MessageBox with the result.
# Usage:  powershell -ExecutionPolicy Bypass -File deploy\make-shortcuts.ps1
param(
    [string]$Root = '',
    [string]$NameStart = 'OpenViking记忆-启动',
    [string]$NameStop = 'OpenViking记忆-停止',
    [switch]$AllUsers,
    [switch]$NoIcons
)
$ErrorActionPreference = 'Stop'
if (-not $Root) { $Root = $PSScriptRoot }
$icons = Join-Path $Root 'icons'
$start = Join-Path $Root 'start_openviking.ps1'
$stop  = Join-Path $Root 'stop_openviking.ps1'
foreach ($f in @($start, $stop)) {
    if (-not (Test-Path $f)) { throw ("missing script: " + $f) }
}

if (-not $NoIcons) {
    $need = @((Join-Path $icons 'ov-start.ico'), (Join-Path $icons 'ov-stop.ico'))
    if ($need | Where-Object { -not (Test-Path $_) }) {
        $mk = Join-Path $Root 'make-icons.ps1'
        if (Test-Path $mk) { & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $mk }
    }
}

$desktop = if ($AllUsers) { [Environment]::GetFolderPath('CommonDesktopDirectory') } else { [Environment]::GetFolderPath('Desktop') }
$ps = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
$shell = New-Object -ComObject WScript.Shell
$specs = @(
    @{ Name = $NameStart; Script = $start; Icon = (Join-Path $icons 'ov-start.ico') },
    @{ Name = $NameStop;  Script = $stop;  Icon = (Join-Path $icons 'ov-stop.ico') }
)
foreach ($s in $specs) {
    $lnk = Join-Path $desktop ($s.Name + '.lnk')
    $sc = $shell.CreateShortcut($lnk)
    $sc.TargetPath = $ps
    $sc.Arguments = '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' + $s.Script + '"'
    $sc.WorkingDirectory = $Root
    $sc.WindowStyle = 7
    $sc.Description = 'OpenViking 长记忆服务'
    if (Test-Path $s.Icon) { $sc.IconLocation = $s.Icon + ",0" }
    $sc.Save()
    Write-Host ("created " + $lnk)
}
